#!/usr/bin/env python3
"""Inspect the BUILT Composer runtime registry and SFZ files; never change routing."""
import json,sys
from pathlib import Path
root=Path('composer/runtime')
registry_path=root/'target_registry.json'
if not registry_path.is_file():
 sys.exit('BUILD_REQUIRED: target_registry.json is generated by build_current_composer.sh')
registry=json.loads(registry_path.read_text())['targets']['INTERNAL']['instrument_bindings']
source=json.loads(Path('composer_overrides/genre_styles/Jazz/SOURCE_RESOURCE_BINDINGS_R1.json').read_text())
candidates={'acoustic_bass':['double_bass'],'kick_drum_soft':['kick_drum_rock:brush_drums'],'brush_snare':['snare_drum:brush_drums']}
result={'mode':'READ_ONLY_NO_ALIASES_INSTALLED','genres':[]}
for genre in source['genres']:
 roles=[]
 for role,spec in genre['role_bindings'].items():
  original=spec['original_instrument_id']
  options=[original]+candidates.get(original,[])
  inspected=[]
  for key in options:
   b=registry.get(key)
   if not b:
    inspected.append({'registry_key':key,'present':False})
    continue
   sfz=root/'sound_resources'/b['resource_id']/b['preferred_mapping']
   inspected.append({'registry_key':key,'present':True,'sfz_exists':sfz.is_file(),'resource_id':b['resource_id'],'sfz':b['preferred_mapping'],'exact_original_id':key==original})
  roles.append({'role':role,'original_id':original,'registry_checks':inspected,'live_binding_changed':False})
 result['genres'].append({'genre':genre['genre'],'roles':roles})
out=Path('jazz-generated-registry-connection-probe');out.mkdir(exist_ok=True)
(out/'report.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps({'genres':len(result['genres']),'exact_present':sum(any(c['present'] and c['exact_original_id'] and c['sfz_exists'] for c in r['registry_checks']) for g in result['genres'] for r in g['roles']),'candidate_present':sum(any(c['present'] and not c['exact_original_id'] and c['sfz_exists'] for c in r['registry_checks']) for g in result['genres'] for r in g['roles'])},indent=2))
