"""Structural & original Rock translator checks for 55 independent style owners.

Each genre owns a unique musical language; MIDI/SFZ rendering stays shared.
An interpreter slot is not a functional interpreter: 54 explicitly BLOCKED.
The recovered 16-bar Rock project-written backend requires exact hash-pinned
MIDI output previously generated by separately licensed external MMA.
"""
from __future__ import annotations
import hashlib,json,re,sys
from pathlib import Path
from collections import Counter
PROJECT=Path(__file__).resolve().parents[1]
ROOT=PROJECT/"composer_overrides"/"genre_styles"
sys.path.insert(0,str(PROJECT/"composer_overrides"))
from genre_styles.shared_interpreter_router import route_to_shared_interpreter
from genre_styles.Rock.rock_pinned_mma_interpreter import (
    compile_pinned_mma_rock_score,PINNED_USER_LIKED_MMA_SHA256,TEMPO,BARS)

def need(ok,msg):
    if not ok:raise AssertionError(msg)

def check_contracts():
    idx=json.loads((ROOT/"index.json").read_text())
    reg=json.loads((ROOT/"GENRE_INTERPRETER_REGISTRY_R1.json").read_text())
    items=idx["genre_to_family_file"]
    need(len(items)==len(reg["per_genre"])==reg["count"]==55,"55_GENRES_MISMATCH")
    need(len({p.split("/")[0] for p in items.values()})==13,"13_FAMILY_DRIFT")
    need(reg["single_shared_output_and_rendering_core"] and
         reg["original_7_stages_unchanged"],"SHARED_CORE_OR_SEVEN_STAGES_CHANGED")
    originals={};count=Counter();files=set()
    for genre,source in items.items():
        entry=reg["per_genre"][genre]
        path=entry["slot_file"]
        need(path not in files,"INTERPRETER_FILENAME_COLLISION:"+path)
        files.add(path)
        slot=json.loads((PROJECT/path).read_text())
        family=source.split("/")[0]
        profile=json.loads((ROOT/source).read_text())["profiles"][genre]
        actual=profile["musical_definition"]
        seq=profile["seven_stage_plan"]
        need(slot["genre_name"]==genre and slot["genre_family"]==family,
             "OTHER_GENRE_TAKING_OWNERSHIP:"+genre)
        need(slot["source_profile_id"]==actual["profile_id"]==entry["profile_id"],
             "WRONG_GENRE_PROFILE_"+genre)
        need(slot["musical_definition_ref"]=={
            "file":"composer_overrides/genre_styles/"+source,
            "json_pointer":"/profiles/"+genre+"/musical_definition",
        },"MUSICAL_DEFINITION_WRONG_XREF:"+genre)
        need(slot["original_seven_stage_ref"]["json_pointer"]==
             "/profiles/"+genre+"/seven_stage_plan" and
             len(seq["stage_order"])==7,"SEVEN_STAGES_NOT_PRESERVED:"+genre)
        need(slot["source_pattern_ref"]["genre_key"]==genre,
             "WRONG_SOURCE_PATTERNS:"+genre)
        need(slot["source_resource_ref"]["genre_key"]==genre,
             "WRONG_SOURCE_RESOURCE:"+genre)
        need(slot["owned_stage_boundary"]==
             "AFTER_STAGE3_INSTRUMENT_SELECTION_BEFORE_STAGE4_COMPOSE",
             "WRONG_INTERPRETER_STAGE:"+genre)
        need(slot["activated_in_live_composer"] is False and
             slot["source_specific_note_score_approved_for_production"] is False,
             "FALSE_LIVE_GENRE_INTERPRETER:"+genre)
        need("inheriting_Rock_notes_into_another_genre" in slot["prohibited"],
             "CROSS_GENRE_FALLBACK_NOT_BLOCKED:"+genre)
        if genre=="ROCK":
            need(slot["backend_file"]=="composer_overrides/genre_styles/Rock/rock_pinned_mma_interpreter.py",
                 "RECOVERED_USER_PREFERRED_ROCK_BACKEND_NOT_OWNED_BY_ROCK")
            need(slot["original_rock_midi_sha256"]==PINNED_USER_LIKED_MMA_SHA256,
                 "USER_PREFERRED_ROCK_MIDI_FINGERPRINT_DRIFT")
        else:
            need(slot["backend_file"] is None and
                 slot["backend_status"]=="EXECUTABLE_GENRE_INTERPRETATION_NOT_YET_IMPLEMENTED",
                 "FALSE_NON_ROCK_INTERPRETER_CLAIM:"+genre)
            count["pending"]+=1
        originals[genre]=actual["profile_id"]
    need(count["pending"]==54 and len(files)==55,"54_BLOCKED_GENRES_NOT_EXPLICIT")
    original=ROOT/"Rock"/"rock_pinned_mma_interpreter.py"
    archive=PROJECT/"research/archived_rock_20261009/original/rock_pinned_mma_interpreter.py"
    strum=ROOT/"Rock"/"rock_strum_phrase_performance.py"
    archived_strum=PROJECT/"research/archived_rock_20261009/original/rock_strum_phrase_performance.py"
    need(original.read_bytes()==archive.read_bytes(),"PINNED_ROCK_TRANSLATOR_WAS_REWRITTEN")
    need(strum.read_bytes()==archived_strum.read_bytes(),"ROCK_STRUM_PERFORMANCE_WAS_REWRITTEN")
    need(TEMPO==145 and BARS==16,"USER_PREFERRED_ROCK_TEMPO_BARS_CHANGED")
    print("ALL_55_GENRE_OWNED_INTERPRETER_SLOTS_PASS",json.dumps({
      "independent_owned_interpreter_contracts":55,
      "family_folders":13,"functional_nonrock_backends_falsely_claimed":0,
      "pending_genre_specific_programs":count["pending"],
      "archived_rock_interpreter_byte_for_byte_restored":True,
      "rock_pinned_source_sha256":PINNED_USER_LIKED_MMA_SHA256,
      "rock_selected_beat_per_minute":TEMPO,
      "original_live_composer_unchanged":True,
      "shared_recorded_resource_and_3d_code_reused":True,
    },sort_keys=True))

def check_pinned_source(path):
    midi=Path(path)
    need(midi.is_file(),"ORIGINAL_USER_PREFERRED_16BAR_MIDI_NOT_RECOVERED")
    need(hashlib.sha256(midi.read_bytes()).hexdigest()==PINNED_USER_LIKED_MMA_SHA256,
         "ORIGINAL_USER_PREFERRED_16BAR_MIDI_CHECKSUM_WRONG")
    stage3={"status":"PASS","palette":["electric_guitar","electric_bass","drums"],
            "meter":"4/4","tempo_bpm":145}
    route=route_to_shared_interpreter("ROCK",original_stage3_result=stage3)
    score=compile_pinned_mma_rock_score(midi,route)
    need(score["status"]=="PINNED_MMA_ROCK_SCORE_INTERPRETED" and
         score["tempo_bpm"]==145 and score["bars"]==16 and
         score["note_count"]==420,
         "RECOVERED_ROCK_INTERPRETER_NOT_PRODUCING_ORIGINAL_SCORE")
    roles=Counter(x["track_id"] for x in score["notes"])
    need(roles==Counter({"HARMONY":225,"BASS":56,"KICK":32,"SNARE":38,
                         "HAT":64,"TOMS":4,"CRASH":1}),
         "USER_APPROVED_MUSIC_PARTS_DRIFTED")
    need(len(score["intent_trace"])==7 and
         score["live_deployed"] is False,
         "LIVE_OR_SECTION_CLAIMS_WRONG")
    print("RECOVERED_USER_LIKED_ROCK_GENRE_INTERPRETER_420_NOTES_PASS",
          json.dumps({"source_sha256":PINNED_USER_LIKED_MMA_SHA256,
          "drum_roles":{"KICK":32,"SNARE":38,"HAT":64,"TOMS":4,"CRASH":1},
          "original_note_counts":dict(roles),
          "original_seven_stage_composer_unchanged":True,
          "no_production_deploy":True},sort_keys=True))

if __name__=="__main__":
    check_contracts()
    if len(sys.argv)==2:check_pinned_source(sys.argv[1])
